### ISSUE TITLE
A local run throws exception

### ISSUE THREAD

**Issue by balajikadambi** [IBM-Cloud/get-started-java#31]
The command mvn install liberty:run-server throws the below error:

[ERROR] Failed to execute goal net.wasdev.wlp.maven.plugins:liberty-maven-plugin:1.2.1:run-server (default-cli) on project GetStartedJava: java.util.zip.ZipException: archive is not a ZIP archive -> [Help 1]

I was following the instructions on IBMCloud documentation:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/25296042/115713876-210e3a80-a394-11eb-9161-11e50d066279.png">

**Comment by balajikadambi** [comment]
I was able to workaround by using the OpenLiberty sample instead to run locally.
https://openliberty.io/downloads/

To deploy to IBM Cloud, I followed the below steps:
- run mvn install
- create a manifest.yml as shown below:
```
---
applications:
 - name: openlibdemo
   random-route: true
   path: target/io.openliberty.sample.getting.started.war
   memory: 512M
   instances: 1
```
- run command ibmcloud cf push
